### ISSUE TITLE
Github auto-updater claims v1.4.0 out

### ISSUE THREAD

**Issue by cheekygit** [Hube2/acf-input-counter#12]
but installs 1.3.1 and keeps nagging about 1.4.0. Setup mistake somewhere?

**Comment by Hube2** [comment]
possibly pulling from release and I didn't create a new release for 1.4.0. Just did it now. Let me know if that solves the issue.

**Comment by cheekygit** [comment]
Nope, no change in what I described.

**Comment by Hube2** [comment]
Look at you list of plugins carefully. Do you have two versions of this plugin installed?

**Comment by cheekygit** [comment]
The update to version 1.4.0 has since worked, thanks
