### ISSUE TITLE
Counter for Wysiwyg ?

### ISSUE THREAD

**Issue by akididou** [Hube2/acf-input-counter#18]
Hi dude,

Is it possible to get a counter for Wysiwyg ?

Peace

**Comment by Hube2** [comment]
There is a fork of this plugin that can be found here https://github.com/puntonero/acf-input-counter.

There are actually several forks that all do different things. I think that these are outside of the scope that I wanted to achieve with this, which was to show a simple example of how to add a counter to text and text area fields that other people could expand on if they chose.

**Comment by rowatt** [comment]
The fork by @puntonero didn't work for me, so I got to rewriting it. If that's helpful to anyone, you can check it out from https://github.com/rowatt/acf-input-counter/

Thank you to @Hube2 for the original code and @puntonero for how to add a counter to wysiwyg fields.

**Comment by brandonpence** [comment]
@rowatt - thanks for doing this!
