### ISSUE TITLE
New small Problem alert Javascript

### ISSUE THREAD

**Issue by sododesign** [Hube2/acf-input-counter#2]
Now when you try to save (in my case options page) appears an empty ALERT preventing saved

**Comment by Hube2** [comment]
I can't recreate this, I don't have any alerts in the JS so I don't know where it's coming from.

**Comment by sododesign** [comment]
Clean installation of WordPress, with installed your Plugin and ACF and Default Theme.

Try to create new post here: http://test.sododesign.it/wp-admin/post-new.php

user: test
pw: test

**Comment by sododesign** [comment]
Hi @Hube2 I found the bug, it seems linked to the title. In the Post Type (Articles in this case), if you leave the title appears the error javascript alert

If I fill out the title instead passes validation and saves. This is not the case in the Options page because there is no title to set, then the error appears more. I hope I explained :)

http://test.sododesign.it/wp-admin/admin.php?page=sample

**Comment by Hube2** [comment]
Give that a test and let me know if that's fixed it

**Comment by sododesign** [comment]
Yes, now work perfect :)

**Comment by sododesign** [comment]
No @Hube2, sorry.

Now the script not count character :(

**Comment by Hube2** [comment]
Try it again, learning when and how to enqueue scripts to extend ACF if nothing else

**Comment by sododesign** [comment]
Thank you very much, in the coming days expect my donation for a beer. it's the least I can do. You've done pretty much everything. Now work perfect
