### ISSUE TITLE
Visual part of tinymce broken

### ISSUE THREAD

**Issue by candell** [Hube2/acf-input-counter#23]
Just a heads up, I installed ACF Input Counter 1.4.0 and ACF 5.6.10 and on activation of ACF Input Counter the visual part of the wysiwyg no longer displays, the text in the field is shown as html and the visual tab no longer works.

**Comment by Hube2** [comment]
Does this has something to do with one of the forks? Tested my version and it's working, the master version does not effect WYSIWYG fields.
