### ISSUE TITLE
Unexpected result with &

### ISSUE THREAD

**Issue by Beee4life** [Hube2/acf-input-counter#24]
I have a text field which is capped at let's say 50 characters.

If I write a title which has 49 characters and includes an &, an error is thrown, since & gets stored as &amp; which is 4 characters more and this not a 'valid input'.

Is there a way around this ???

**Comment by Hube2** [comment]
I don't know if there's anything that can be done or not. I'll look into it when I can.

**Comment by Beee4life** [comment]
I understand... no rush

**Comment by Beee4life** [comment]
Did you ever find some time to check this ?

**Comment by Hube2** [comment]
No, to be honest, I haven't. I actually forgot about it. Life has been really busy for me. To be completely honest, it's not something I use. If anyone else wants to look at this and contribute to it, that would be the fastest way to get it done.

**Comment by Beee4life** [comment]
I was more wondering tbh. The project where this occurred is from a previous employer, so I'm not coming across it anymore ;) So will close it for now.
